project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
        - section: "Project"
          contents:
            - href: index.qmd
              text: Home
        - section: "About"
          contents:
          - href: about.qmd
            text: Team
          - text: Github
            href: https://github.com/STA6257-Missing-Data-and-Imputation/MissingDataAndImputation

      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



