project:
  type: website
  output-dir: docs

website:
  sidebar:
    tools:
      - icon: house
        href: index.qmd
      - icon: github
        href: https://github.com/STA6257-Missing-Data-and-Imputation/MissingDataAndImputation

    style: "docked"
    search: true

    contents:
        - section: "Project"
          contents:
            - href: intro.qmd
              text: Introduction
            - href: data.qmd
              text: Data
            - href: methodology.qmd
              text: Methodology
            - href: analysis.qmd
              text: Analysis
            - href: conclusion.qmd
              text: Conclusion
        - section: "Presentation"
          contents:
            - href: slides/slidedeck.qmd
              target: _blank
              text: Slide Deck
              
        - section: "About"
          contents:
          - href: about.qmd
            text: Team

      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



