---
title: "2. Data"
bibliography: references.bib
css: styles.css
---

This project will focus on the penguin dataset in the "palmerpenguin" package [@palmerpenguins] from R studio. The penguins' dataset is comprised of 8 columns and 344 rows based on data collected on three different species of penguins in Palmer Archipelago, Antarctica. This dataset is fairly clean, and this is important for comparison purposes. In this instance, there are only 11 NA values, which is 3% of the entire dataset. During the analysis, we will be removing parts of the dataset and implementing data imputation methodology to compare the accuracy between the actual values in the dataset and the calculated values we have created using different methodologies.

## 2.1 Variables

-   Species - defines the species of the penguins as Adelie, Chinstrap, or Gentoo
-   Island - what island (Biscoe, Dream, or Torgersen) the penguins were found in the Palmer Archipelago, Antarctica
-   Bill_length_mm - a number indicating bill length in millimeters
-   Bill_depth_mm - a number indicating bill depth in millimeters
-   Flipper_length_mm - an integer indicating flipper length in millimeters
-   Body_mass_g - an integer indicating body mass in grams
-   Sex - a factor that marks the penguins as female or male
-   Year - an integer that defines the study year as 2007, 2008, or 2009

A visual depiction of how bill length and depth is measured:

[![[@palmerpenguins] Artwork by \@allison_horst](imgs/culmen_depth.png){fig-align="center"}](https://allisonhorst.github.io/palmerpenguins/)

## 2.2 Data Exploration

Below is a summary of the palmerpenguins dataset [@palmerpenguins] using the summarytools [@summarytools] package and visualizations from the palmerpenguins package. [@palmerpenguins]

```{r}
#Shows the first six rows of the data set
library(palmerpenguins)
data(package = 'palmerpenguins')
head(penguins)

#Shows all the variables in the data set 
str(penguins)

#Describes the penguins data set
library(summarytools)
descr(penguins)

```
